In [4]:
import os
import pandas as pd

# On remonte d'un dossier (..) pour atteindre unified_textual_description
base_dir = "../unified_textual_description"

data = []

for root, dirs, files in os.walk(base_dir):
    for file in files:
        if file.endswith(".txt"):
            file_path = os.path.join(root, file)
            
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    text_content = f.read().strip()
                    
                    # On stocke le dossier parent et le nom du fichier
                    dossier_parent = os.path.basename(root)
                    source = f"{dossier_parent}/{file}"
                    
                    data.append({
                        "fichier_source": source,
                        "texte_original": text_content
                    })
            except Exception as e:
                print(f"Erreur lors de la lecture de {file_path} : {e}")

df = pd.DataFrame(data)
df["bpmn_genere"] = None

print(f"Nombre total de textes chargés : {len(df)}")
print(df.head())

Nombre total de textes chargés : 163
         fichier_source                                     texte_original  \
0  PAGED/1934621887.txt  For Personal Users: To begin, send a request f...
1  PAGED/1329958954.txt  To start the Meeting Scheduler process, begin ...
2  PAGED/1235925705.txt  To begin the process, the Resupply Cycle is tr...
3  PAGED/1352840228.txt  To begin the process for ACME Company, you sho...
4  PAGED/1286652977.txt  In the beginning, a loan request is created an...

  bpmn_genere
0        None
1        None
2        None
3        None
4        None

In [27]:
df

,fichier_source,texte_original,bpmn_genere,texte_reformule_llama_3_3_70b_instruct,latence_secondes_llama_3_3_70b_instruct,prompt_tokens_llama_3_3_70b_instruct,completion_tokens_llama_3_3_70b_instruct,total_tokens_llama_3_3_70b_instruct,finish_reason_llama_3_3_70b_instruct,statut_llama_3_3_70b_instruct,...,total_tokens_mistral-small-4-119b-2603,finish_reason_mistral-small-4-119b-2603,statut_mistral-small-4-119b-2603,texte_reformule_ministral-14b-instruct-2512,latence_secondes_ministral-14b-instruct-2512,prompt_tokens_ministral-14b-instruct-2512,completion_tokens_ministral-14b-instruct-2512,total_tokens_ministral-14b-instruct-2512,finish_reason_ministral-14b-instruct-2512,statut_ministral-14b-instruct-2512
0,PAGED/1934621887.txt,"For Personal Users: To begin, send a request f...",None,The process begins when a request for account ...,14.99,507.0,491.0,998.0,stop,Succès,...,1032,stop,Succès,### **Reformulated Process: Personal User Acco...,67.03,488,1024,1512,length,Succès
1,PAGED/1329958954.txt,"To start the Meeting Scheduler process, begin ...",None,The Meeting Scheduler process begins when a me...,9.61,264.0,176.0,440.0,stop,Succès,...,479,stop,Succès,"Here’s a refined, structured, and logically co...",44.01,245,662,907,stop,Succès
2,PAGED/1235925705.txt,"To begin the process, the Resupply Cycle is tr...",None,The process begins when the Resupply Cycle is ...,13.11,401.0,324.0,725.0,stop,Succès,...,950,stop,Succès,"Here is the refined, structured, and professio...",11.98,386,857,1243,stop,Succès
3,PAGED/1352840228.txt,"To begin the process for ACME Company, you sho...",None,The process for ACME Company begins when the r...,16.69,493.0,394.0,887.0,stop,Succès,...,807,stop,Succès,### **Reformulated & Structured Process: ACME ...,14.02,472,1024,1496,length,Succès
4,PAGED/1286652977.txt,"In the beginning, a loan request is created an...",None,The process begins when a loan request is crea...,7.31,382.0,255.0,637.0,stop,Succès,...,734,stop,Succès,"Here’s a structured, precise, and logically or...",58.77,366,853,1219,stop,Succès
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Text_and_BPMN_Zenodo/V_g01.txt,Category: Vending and Shipping\nTitle: Robotic...,None,The process begins when the robotic burger sel...,37.96,386.0,314.0,700.0,stop,Succès,...,851,stop,Succès,### **Reformulated Process: Robotic Burger Ord...,13.56,385,1024,1409,length,Succès
159,Camunda_BPMN4Research/EN_Ex4.txt,Background \nA self-service restaurant is unde...,None,The optimized process for the self-service res...,5.63,586.0,405.0,991.0,stop,Succès,...,1237,stop,Succès,### **Optimized Self-Service Restaurant Proces...,15.8,700,1020,1720,stop,Succès
160,Camunda_BPMN4Research/EN_Ex3.txt,Background \nA credit protection agency (in Ge...,None,The process begins when a sales clerk in a ban...,8.97,524.0,459.0,983.0,stop,Succès,...,1105,stop,Succès,### **Reformulated Process Description: Credit...,9.06,545,686,1231,stop,Succès
161,Camunda_BPMN4Research/EN_Ex2.txt,Please model the following process: \nIf an i...,None,The process begins when a potential subrogatio...,22.08,421.0,339.0,760.0,stop,Succès,...,743,stop,Succès,### **Process: Recourse Management (Subrogatio...,12.86,418,972,1390,stop,Succès
162,Camunda_BPMN4Research/EN_Ex1.txt,Please model the following process \nIf goods...,None,The process begins when a decision is made to ...,14.04,379.0,298.0,677.0,stop,Succès,...,976,stop,Succès,"### **Reformulated & Structured Process: ""Good...",13.58,381,1024,1405,length,Succès

In [49]:
# Exporter le DataFrame en fichier CSV
df.to_csv("resultats_reformulation_V11.csv", index=False, encoding="utf-8")

In [6]:
from openai import OpenAI

client = OpenAI(
  base_url = "https://integrate.api.nvidia.com/v1",
  api_key = "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"
)

completion = client.chat.completions.create(
  model="meta/llama-3.3-70b-instruct",
  messages=[{"role":"user","content":"salut"}],
  temperature=0.2,
  top_p=0.7,
  max_tokens=1024,
  stream=True
)

for chunk in completion:
  if chunk.choices and chunk.choices[0].delta.content is not None:
    print(chunk.choices[0].delta.content, end="")

Salut! Comment puis-je vous aider aujourd'hui ?

In [7]:
from openai import OpenAI
import pandas as pd
import time

# 1. Initialisation du client
client = OpenAI(
  base_url = "https://integrate.api.nvidia.com/v1",
  api_key = "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"
)

# 2. Définition de la fonction avec métriques
def reformulate_process_text(texte_original):
    system_prompt = """You are an experienced process owner in a leading company.

Considering the context of Business Process Management (BPM) and process modeling:
- Process: Describes a sequence or flow of activities in an organization.

You are given a possibly incomplete process description delimited by '''. Analyze the description, then reformulate it. Your reformulation should be precise, clear and structured.

Follow these instructions:
- Add all possible termination points.
- Ensure the logical order of steps is clear.
- Use standard, professional terminology.

Here are some examples:
<<
Input: 
'''When a manuscript gets the green light for publication, the editors swing into action. If it passes muster, they give a heads-up to the production and design crews.'''

Output: 
The process begins when a manuscript is approved. The editors then review the manuscript. If the manuscript passes the review, the editors notify the production and design teams. If the manuscript does not pass the review, the process ends.
>>"""

    user_prompt = f"Process description: ''' {texte_original} '''"

    # Démarrage du chronomètre
    start_time = time.time()

    try:
        completion = client.chat.completions.create(
            model="meta/llama-3.3-70b-instruct",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,
            top_p=0.7,
            max_tokens=1024,
            stream=False
        )
        
        # Arrêt du chronomètre
        end_time = time.time()
        
        # Extraction des données
        texte_genere = completion.choices[0].message.content.strip()
        finish_reason = completion.choices[0].finish_reason
        
        # Extraction sécurisée des tokens via l'API
        prompt_tokens = completion.usage.prompt_tokens if completion.usage else 0
        completion_tokens = completion.usage.completion_tokens if completion.usage else 0
        total_tokens = completion.usage.total_tokens if completion.usage else 0
        
        return {
            "texte_reformule": texte_genere,
            "latence_secondes": round(end_time - start_time, 2),
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens,
            "finish_reason": finish_reason,
            "statut": "Succès"
        }
        
    except Exception as e:
        end_time = time.time()
        return {
            "texte_reformule": None,
            "latence_secondes": round(end_time - start_time, 2),
            "prompt_tokens": None,
            "completion_tokens": None,
            "total_tokens": None,
            "finish_reason": None,
            "statut": f"Erreur: {str(e)}"
        }

# 3. Application sur le DataFrame et collecte des métriques
print("Début de la reformulation et du benchmarking...")

# Liste pour stocker tous les dictionnaires de résultats
resultats = []

for index, row in df.iterrows():
    print(f"Traitement {index + 1}/{len(df)} : {row['fichier_source']}")
    res = reformulate_process_text(row['texte_original'])
    resultats.append(res)
    # Optionnel: time.sleep(0.5) pour éviter de saturer l'API Nvidia si nécessaire

# 4. Intégration des résultats dans le DataFrame
# Convertir la liste de dictionnaires en DataFrame temporaire
df_metrics = pd.DataFrame(resultats)

# Concaténer (joindre) le DataFrame original avec le DataFrame des métriques
df = pd.concat([df, df_metrics], axis=1)

print("Reformulation terminée !")
# Afficher un résumé des performances (ex: latence moyenne)
print(f"\nLatence moyenne : {df['latence_secondes'].mean():.2f} secondes")
print(f"Tokens générés en moyenne : {df['completion_tokens'].mean():.0f}")

# Visualiser les colonnes générées
print(df.head())

Début de la reformulation et du benchmarking...
Traitement 1/163 : PAGED/1934621887.txt
Traitement 2/163 : PAGED/1329958954.txt
Traitement 3/163 : PAGED/1235925705.txt
Traitement 4/163 : PAGED/1352840228.txt
Traitement 5/163 : PAGED/1286652977.txt
Traitement 6/163 : PAGED/1226498320.txt
Traitement 7/163 : PAGED/1473806539.txt
Traitement 8/163 : PAGED/1337645986.txt
Traitement 9/163 : PAGED/1409572751.txt
Traitement 10/163 : PAGED/1940833472.txt
Traitement 11/163 : PAGED/1309672350.txt
Traitement 12/163 : PAGED/1233431981.txt
Traitement 13/163 : PAGED/1410268331.txt
Traitement 14/163 : PAGED/1191144576.txt
Traitement 15/163 : PAGED/1195286382.txt
Traitement 16/163 : PAGED/1241042198.txt
Traitement 17/163 : PAGED/1467107206.txt
Traitement 18/163 : PAGED/1425006907.txt
Traitement 19/163 : PAGED/1283995127.txt
Traitement 20/163 : PAGED/1467836466.txt
Traitement 21/163 : PAGED/1247939176.txt
Traitement 22/163 : PAGED/1383686290.txt
Traitement 23/163 : PAGED/1900639740.txt
Traitement 24/163 : PAGED/1900538815.txt
Traitement 25/163 : PAGED/1290321174.txt
Traitement 26/163 : PAGED/1361468541.txt
Traitement 27/163 : PAGED/1314718328.txt
Traitement 28/163 : PAGED/1468373358.txt
Traitement 29/163 : PAGED/1907085906.txt
Traitement 30/163 : PAGED/1228639130.txt
Traitement 31/163 : PAGED/1904148439.txt
Traitement 32/163 : PAGED/1226133062.txt
Traitement 33/163 : PAGED/1188157819.txt
Traitement 34/163 : PAGED/1376709591.txt
Traitement 35/163 : PAGED/1429084667.txt
Traitement 36/163 : PAGED/1339604510.txt
Traitement 37/163 : PAGED/1288790214.txt
Traitement 38/163 : PAGED/1381696062.txt
Traitement 39/163 : PAGED/1479161968.txt
Traitement 40/163 : PAGED/1414026620.txt
Traitement 41/163 : PAGED/1192409168.txt
Traitement 42/163 : PAGED/1299931035.txt
Traitement 43/163 : PAGED/1237501896.txt
Traitement 44/163 : PAGED/1340845012.txt
Traitement 45/163 : PAGED/1263880376.txt
Traitement 46/163 : MaD/churn_rate_prevention_process_churn_rate_prevention_process_55.txt
Traitement 47/163 : MaD/employee_onboarding_process_employee_onboarding_process_185.txt
Traitement 48/163 : MaD/final_grades_submission_process_final grades submission process_172.txt
Traitement 49/163 : MaD/churn_rate_prevention_process_churn_rate_prevention_process_102.txt
Traitement 50/163 : MaD/process_for_optimizing_a_process_process_for_optimizing_a_process_70.txt
Traitement 51/163 : MaD/content_promotion_process_content_promotion_process_77.txt
Traitement 52/163 : MaD/accounts_receivable_process_accounts_receivable_process_135.txt
Traitement 53/163 : MaD/accounts_receivable_process_accounts_receivable_process_122.txt
Traitement 54/163 : MaD/startup_due_diligence_for_a_venture_capitalist_startup_due_diligence_for_a_venture_capitalist_86.txt
Traitement 55/163 : MaD/customer_support_process_for_the_ticket_management_customer_support_process_for_the_ticket_management_76.txt
Traitement 56/163 : MaD/client_onboarding_process_for_a_marketing_agency_client_onboarding_process_for_a_marketing_agency_170.txt
Traitement 57/163 : MaD/startup_due_diligence_for_a_venture_capitalist_startup_due_diligence_for_a_venture_capitalist_145.txt
Traitement 58/163 : MaD/order_fulfillment_process_order_fulfillment_process_118.txt
Traitement 59/163 : MaD/account_payable_process_account_payable_process_117.txt
Traitement 60/163 : MaD/final_grades_submission_process_final grades submission process_38.txt
Traitement 61/163 : MaD/customer_support_process_for_the_ticket_management_customer_support_process_for_the_ticket_management_108.txt
Traitement 62/163 : MaD/churn_rate_prevention_process_churn_rate_prevention_process_35.txt
Traitement 63/163 : MaD/final_grades_submission_process_final grades submission process_107.txt
Traitement 64/163 : MaD/budget_preparation_process_budget_preparation_process_189.txt
Traitement 65/163 : MaD/employee_onboarding_process_employee_onboarding_process_104.txt
Traitement 66/163 : MaD/account_payable_process_account_payable_process_44.txt
Traitement 67/163 : MaD/project_management_process_project_management_process_95.txt
Traitement 68/163 : MaD/startup_due_diligence_for_a_venture_capitalist_startup_due_diligence_for_a_venture_capitalist_65.txt
Traitement 69/163 : MaD/loan_application_process_loan_application_process_97.txt
Traitement 70/163 : MaD/employee_onboarding_process_employee_onboarding_process_113.txt
Traitement 71/163 : MaD/order_fulfillment_process_order_fulfillment_process_106.txt
Traitement 72/163 : MaD/process_for_optimizing_a_process_process_for_optimizing_a_process_4.txt
Traitement 73/163 : MaD/client_onboarding_process_for_a_marketing_agency_client_onboarding_process_for_a_marketing_agency_61.txt
Traitement 74/163 : MaD/loan_application_process_loan_application_process_45.txt
Traitement 75/163 : MaD/content_promotion_process_content_promotion_process_103.txt
Traitement 76/163 : MaD/purchase_order_workflow_purchase_order_workflow_158.txt
Traitement 77/163 : MaD/accounts_receivable_process_accounts_receivable_process_48.txt
Traitement 78/163 : MaD/budget_preparation_process_budget_preparation_process_143.txt
Traitement 79/163 : MaD/account_payable_process_account_payable_process_126.txt
Traitement 80/163 : MaD/project_management_process_project_management_process_85.txt
Traitement 81/163 : MaD/process_for_optimizing_a_process_process_for_optimizing_a_process_21.txt
Traitement 82/163 : MaD/budget_preparation_process_budget_preparation_process_195.txt
Traitement 83/163 : MaD/client_onboarding_process_for_a_marketing_agency_client_onboarding_process_for_a_marketing_agency_10.txt
Traitement 84/163 : MaD/purchase_order_workflow_purchase_order_workflow_9.txt
Traitement 85/163 : MaD/customer_support_process_for_the_ticket_management_customer_support_process_for_the_ticket_management_161.txt
Traitement 86/163 : MaD/order_fulfillment_process_order_fulfillment_process_0.txt
Traitement 87/163 : MaD/content_promotion_process_content_promotion_process_165.txt
Traitement 88/163 : MaD/project_management_process_project_management_process_33.txt
Traitement 89/163 : MaD/purchase_order_workflow_purchase_order_workflow_111.txt
Traitement 90/163 : MaD/loan_application_process_loan_application_process_30.txt
Traitement 91/163 : PET/doc-5.2.txt
Traitement 92/163 : PET/doc-3.5.txt
Traitement 93/163 : PET/doc-5.3.txt
Traitement 94/163 : PET/doc-7.1.txt
Traitement 95/163 : PET/doc-5.1.txt
Traitement 96/163 : PET/doc-3.7.txt
Traitement 97/163 : PET/doc-1.4.txt
Traitement 98/163 : PET/doc-3.6.txt
Traitement 99/163 : PET/doc-5.4.txt
Traitement 100/163 : PET/doc-3.2.txt
Traitement 101/163 : PET/doc-1.1.txt
Traitement 102/163 : PET/doc-3.3.txt
Traitement 103/163 : PET/doc-3.1.txt
Traitement 104/163 : PET/doc-1.3.txt
Traitement 105/163 : PET/doc-1.2.txt
Traitement 106/163 : PET/doc-10.4.txt
Traitement 107/163 : PET/doc-4.1.txt
Traitement 108/163 : PET/doc-6.3.txt
Traitement 109/163 : PET/doc-6.2.txt
Traitement 110/163 : PET/doc-10.5.txt
Traitement 111/163 : PET/doc-10.7.txt
Traitement 112/163 : PET/doc-6.1.txt
Traitement 113/163 : PET/doc-10.6.txt
Traitement 114/163 : PET/doc-10.2.txt
Traitement 115/163 : PET/doc-2.1.txt
Traitement 116/163 : PET/doc-6.4.txt
Traitement 117/163 : PET/doc-10.3.txt
Traitement 118/163 : PET/doc-10.1.txt
Traitement 119/163 : PET/doc-2.2.txt
Traitement 120/163 : PET/doc-8.3.txt
Traitement 121/163 : PET/doc-8.2.txt
Traitement 122/163 : PET/doc-10.8.txt
Traitement 123/163 : PET/doc-8.1.txt
Traitement 124/163 : PET/doc-10.9.txt
Traitement 125/163 : PET/doc-10.12.txt
Traitement 126/163 : PET/doc-10.13.txt
Traitement 127/163 : PET/doc-9.5.txt
Traitement 128/163 : PET/doc-10.11.txt
Traitement 129/163 : PET/doc-10.10.txt
Traitement 130/163 : PET/doc-9.4.txt
Traitement 131/163 : PET/doc-10.14.txt
Traitement 132/163 : PET/doc-9.1.txt
Traitement 133/163 : PET/doc-9.3.txt
Traitement 134/163 : PET/doc-3.8.txt
Traitement 135/163 : PET/doc-9.2.txt
Traitement 136/163 : Text_and_BPMN_Zenodo/G_g03.txt
Traitement 137/163 : Text_and_BPMN_Zenodo/G_g01.txt
Traitement 138/163 : Text_and_BPMN_Zenodo/R_g01.txt
Traitement 139/163 : Text_and_BPMN_Zenodo/M_g02.txt
Traitement 140/163 : Text_and_BPMN_Zenodo/X_g03.txt
Traitement 141/163 : Text_and_BPMN_Zenodo/M_g01.txt
Traitement 142/163 : Text_and_BPMN_Zenodo/X_g01.txt
Traitement 143/163 : Text_and_BPMN_Zenodo/R_j03.txt
Traitement 144/163 : Text_and_BPMN_Zenodo/R_j02.txt
Traitement 145/163 : Text_and_BPMN_Zenodo/G_j01.txt
Traitement 146/163 : Text_and_BPMN_Zenodo/R_j01.txt
Traitement 147/163 : Text_and_BPMN_Zenodo/R_j04.txt
Traitement 148/163 : Text_and_BPMN_Zenodo/M_k05.txt
Traitement 149/163 : Text_and_BPMN_Zenodo/V_k08.txt
Traitement 150/163 : Text_and_BPMN_Zenodo/E_j05.txt
Traitement 151/163 : Text_and_BPMN_Zenodo/M_j03.txt
Traitement 152/163 : Text_and_BPMN_Zenodo/M_j02.txt
Traitement 153/163 : Text_and_BPMN_Zenodo/E_j04.txt
Traitement 154/163 : Text_and_BPMN_Zenodo/V_k09.txt
Traitement 155/163 : Text_and_BPMN_Zenodo/M_j01.txt
Traitement 156/163 : Text_and_BPMN_Zenodo/E_j03.txt
Traitement 157/163 : Text_and_BPMN_Zenodo/E_j02.txt
Traitement 158/163 : Text_and_BPMN_Zenodo/E_j01.txt
Traitement 159/163 : Text_and_BPMN_Zenodo/V_g01.txt
Traitement 160/163 : Camunda_BPMN4Research/EN_Ex4.txt
Traitement 161/163 : Camunda_BPMN4Research/EN_Ex3.txt
Traitement 162/163 : Camunda_BPMN4Research/EN_Ex2.txt
Traitement 163/163 : Camunda_BPMN4Research/EN_Ex1.txt
Reformulation terminée !

Latence moyenne : 13.53 secondes
Tokens générés en moyenne : 301
         fichier_source                                     texte_original  \
0  PAGED/1934621887.txt  For Personal Users: To begin, send a request f...
1  PAGED/1329958954.txt  To start the Meeting Scheduler process, begin ...
2  PAGED/1235925705.txt  To begin the process, the Resupply Cycle is tr...
3  PAGED/1352840228.txt  To begin the process for ACME Company, you sho...
4  PAGED/1286652977.txt  In the beginning, a loan request is created an...

  bpmn_genere                                    texte_reformule  \
0        None  The process begins when a request for account ...
1        None  The Meeting Scheduler process begins when a me...
2        None  The process begins when the Resupply Cycle is ...
3        None  The process for ACME Company begins when the r...
4        None  The process begins when a loan request is crea...

   latence_secondes  prompt_tokens  completion_tokens  total_tokens  \
0             14.99          507.0              491.0         998.0
1              9.61          264.0              176.0         440.0
2             13.11          401.0              324.0         725.0
3             16.69          493.0              394.0         887.0
4              7.31          382.0              255.0         637.0

  finish_reason  statut
0          stop  Succès
1          stop  Succès
2          stop  Succès
3          stop  Succès
4          stop  Succès

In [50]:
import pandas as pd

# 1. Définition de la liste complète de vos 4 modèles testés
model_suffixes = [
    "_llama_3_3_70b_instruct", #nim
    #"_llama-3.2-3b-instruct", #nim
    "_llama-3.1-8b-instruct", #nim
    "_mistral-small-4-119b-2603", #nim
    "_gpt-oss-20b", #nim
    "_gpt-oss-120b", #nim
    "_mistral-small-4-119b-2603", #nim
    "_kimi-k2.6", #nim
    "_nvidia-nemotron-nano-9b-v2", #nim
    "_qwen3-coder-480b-a35b-instruct"
]

# Listes pour stocker les métriques globales et construire le tableau comparatif
summary_data = []

print("=== ANALYSE COMPARATIVE DES PERFORMANCES DE REFORMULATION ===\n")

# 2. Boucle d'analyse par modèle
for suffix in model_suffixes:
    colonne_statut = f"statut{suffix}"
    colonne_latence = f"latence_secondes{suffix}"
    colonne_tokens = f"completion_tokens{suffix}"
    
    # Sécurité : on vérifie si le modèle a bien été exécuté (si la colonne existe)
    if colonne_statut not in df.columns:
        print(f"⚠️ Le modèle '{suffix.strip('_')}' n'a pas encore de données d'exécution détectées.\n")
        continue
        
    # Calcul des métriques de succès
    nb_total = len(df)
    nb_succes = (df[colonne_statut] == "Succès").sum()
    nb_echecs = nb_total - nb_succes
    ratio_succes = nb_succes / nb_total if nb_total > 0 else 0
    pourcentage_succes = ratio_succes * 100
    
    # Calcul des moyennes de performance (latence et tokens générés)
    latence_moyenne = df[colonne_latence].mean() if colonne_latence in df.columns else 0
    tokens_moyens = df[colonne_tokens].mean() if colonne_tokens in df.columns else 0

    # Stockage pour le tableau récapitulatif final
    summary_data.append({
        "Modèle": suffix.strip('_'),
        "Total Traité": nb_total,
        "Succès": nb_succes,
        "Échecs": nb_echecs,
        "Taux de Succès (%)": round(pourcentage_succes, 2),
        "Latence Moyenne (s)": round(latence_moyenne, 2),
        "Moyenne Tokens Générés": round(tokens_moyens, 1)
    })

    # Affichage du rapport textuel détaillé pour ce modèle
    print(f"📊 Modèle : {suffix.strip('_')}")
    print(f" ├─ Score : {nb_succes}/{nb_total} réussites ({pourcentage_succes:.2f}%)")
    print(f" ├─ Vitesse : Latence moyenne de {latence_moyenne:.2f} secondes")
    print(f" └─ Volume  : {tokens_moyens:.1f} tokens générés en moyenne")
    
    print("\n🔍 Détail des statuts et erreurs :")
    repartition = df[colonne_statut].value_counts(normalize=True) * 100
    for statut, pct in repartition.items():
        print(f"  └─ {statut} : {pct:.2f}%")
    print("-" * 60 + "\n")

# 3. Génération et affichage du tableau de synthèse global
print("=== TABLEAU COMPARATIF FINAL ===")
df_comparatif = pd.DataFrame(summary_data)

# Trie automatiquement par le meilleur taux de succès, puis par la meilleure latence
df_comparatif = df_comparatif.sort_values(by=["Taux de Succès (%)", "Latence Moyenne (s)"], ascending=[False, True])

# Affichage propre sous forme de table Pandas
display(df_comparatif)

=== ANALYSE COMPARATIVE DES PERFORMANCES DE REFORMULATION ===

📊 Modèle : llama_3_3_70b_instruct
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 22.86 secondes
 └─ Volume  : 321.7 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : llama-3.1-8b-instruct
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 1.91 secondes
 └─ Volume  : 282.6 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : mistral-small-4-119b-2603
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 7.62 secondes
 └─ Volume  : 399.2 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : gpt-oss-20b
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 5.30 secondes
 └─ Volume  : 973.5 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : gpt-oss-120b
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 5.78 secondes
 └─ Volume  : 909.6 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : mistral-small-4-119b-2603
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 7.62 secondes
 └─ Volume  : 399.2 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : kimi-k2.6
 ├─ Score : 29/163 réussites (17.79%)
 ├─ Vitesse : Latence moyenne de 20.42 secondes
 └─ Volume  : 287.3 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

📊 Modèle : nvidia-nemotron-nano-9b-v2
 ├─ Score : 100/163 réussites (61.35%)
 ├─ Vitesse : Latence moyenne de 17.44 secondes
 └─ Volume  : 949.5 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 61.35%
  └─ Erreur: 'NoneType' object has no attribute 'strip' : 38.65%
------------------------------------------------------------

📊 Modèle : qwen3-coder-480b-a35b-instruct
 ├─ Score : 163/163 réussites (100.00%)
 ├─ Vitesse : Latence moyenne de 11.98 secondes
 └─ Volume  : 286.2 tokens générés en moyenne

🔍 Détail des statuts et erreurs :
  └─ Succès : 100.00%
------------------------------------------------------------

=== TABLEAU COMPARATIF FINAL ===

,Modèle,Total Traité,Succès,Échecs,Taux de Succès (%),Latence Moyenne (s),Moyenne Tokens Générés
1,llama-3.1-8b-instruct,163,163,0,100.00,1.91,282.6
3,gpt-oss-20b,163,163,0,100.00,5.30,973.5
4,gpt-oss-120b,163,163,0,100.00,5.78,909.6
2,mistral-small-4-119b-2603,163,163,0,100.00,7.62,399.2
5,mistral-small-4-119b-2603,163,163,0,100.00,7.62,399.2
8,qwen3-coder-480b-a35b-instruct,163,163,0,100.00,11.98,286.2
0,llama_3_3_70b_instruct,163,163,0,100.00,22.86,321.7
7,nvidia-nemotron-nano-9b-v2,163,100,63,61.35,17.44,949.5
6,kimi-k2.6,163,29,134,17.79,20.42,287.3

In [11]:
import time

print("Reprise des textes en échec...")

# On ne boucle que sur les lignes qui n'ont pas le statut "Succès"
lignes_en_echec = df[df['statut'] != "Succès"].index

for index in lignes_en_echec:
    row = df.loc[index]
    print(f"Nouvelle tentative pour le fichier : {row['fichier_source']}")
    
    max_retries = 3
    for attempt in range(max_retries):
        res = reformulate_process_text(row['texte_original'])
        
        if res['statut'] == "Succès":
            # Si ça marche, on met à jour les colonnes de cette ligne dans le DataFrame
            for key, value in res.items():
                df.at[index, key] = value
            print(" -> Succès !")
            break # On sort de la boucle de retries
            
        elif "429" in res['statut']:
            # Si on se reprend un 429, on attend plus longtemps (ex: 5 secondes)
            print(f" -> Rate limit atteint. Pause de 5 secondes... (Tentative {attempt + 1}/{max_retries})")
            time.sleep(5)
            
        else:
            # Si c'est une autre erreur, on la note et on passe au texte suivant
            for key, value in res.items():
                df.at[index, key] = value
            print(f" -> Autre erreur : {res['statut']}")
            break
            
    # Pause préventive de 2 secondes entre CHAQUE requête réussie pour ne pas saturer l'API
    time.sleep(2)

# --- On recalcule le bilan pour voir où on en est ---
print("\n--- Nouveau Bilan de la reformulation ---")
nb_total = len(df)
nb_succes = (df['statut'] == "Succès").sum()
nb_echecs = nb_total - nb_succes
ratio_succes = nb_succes / nb_total if nb_total > 0 else 0

print(f"Total des textes traités : {nb_total}")
print(f"Nombre de succès         : {nb_succes}")
print(f"Nombre d'échecs          : {nb_echecs}")
print(f"Ratio de succès          : {ratio_succes:.2f} soit {ratio_succes*100:.2f}%\n")

# Sauvegarde de sécurité
df.to_csv("resultats_reformulation_complet.csv", index=False, encoding="utf-8")
print("Sauvegarde effectuée dans 'resultats_reformulation_complet.csv'")

Reprise des textes en échec...
Nouvelle tentative pour le fichier : MaD/purchase_order_workflow_purchase_order_workflow_158.txt
 -> Succès !
Nouvelle tentative pour le fichier : MaD/budget_preparation_process_budget_preparation_process_143.txt
 -> Succès !
Nouvelle tentative pour le fichier : MaD/loan_application_process_loan_application_process_30.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-5.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-3.7.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-1.4.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-3.6.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-5.4.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-3.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-1.3.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-1.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.4.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-4.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-6.3.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-6.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.5.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.7.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-6.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.2.txt
 -> Rate limit atteint. Pause de 5 secondes... (Tentative 1/3)
 -> Rate limit atteint. Pause de 5 secondes... (Tentative 2/3)
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-2.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-6.4.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.3.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-2.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-8.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.8.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-8.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.9.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.12.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.13.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-9.5.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.11.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.10.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-9.4.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-10.14.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-9.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-9.3.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-3.8.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-9.2.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/G_g03.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/G_g01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/R_g01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/M_g02.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/X_g03.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/M_g01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/X_g01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/R_j03.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/R_j02.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/G_j01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/R_j01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/R_j04.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/M_k05.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/V_k08.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/E_j05.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/M_j03.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/M_j02.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/E_j04.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/V_k09.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/M_j01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/E_j03.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/E_j02.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/E_j01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Text_and_BPMN_Zenodo/V_g01.txt
 -> Succès !
Nouvelle tentative pour le fichier : Camunda_BPMN4Research/EN_Ex4.txt
 -> Succès !
Nouvelle tentative pour le fichier : Camunda_BPMN4Research/EN_Ex3.txt
 -> Succès !
Nouvelle tentative pour le fichier : Camunda_BPMN4Research/EN_Ex2.txt
 -> Succès !
Nouvelle tentative pour le fichier : Camunda_BPMN4Research/EN_Ex1.txt
 -> Succès !

--- Nouveau Bilan de la reformulation ---
Total des textes traités : 163
Nombre de succès         : 163
Nombre d'échecs          : 0
Ratio de succès          : 1.00 soit 100.00%

Sauvegarde effectuée dans 'resultats_reformulation_complet.csv'

In [34]:
import time

# Configuration avec ton suffixe exact
suffix = "_gpt-oss-20b"
colonne_statut = f"statut{suffix}"

print("Reprise des textes en échec pour openai/gpt-oss-20b...")

# On isole uniquement les 17 lignes en échec pour ce modèle
lignes_en_echec = df[df[colonne_statut] != "Succès"].index

for index in lignes_en_echec:
    row = df.loc[index]
    print(f"Nouvelle tentative pour le fichier : {row['fichier_source']}")
    
    max_retries = 3
    for attempt in range(max_retries):
        # Utilise ta fonction existante (qui appelle bien openai/gpt-oss-20b)
        res = reformulate_process_text(row['texte_original']) 
        
        if res['statut'] == "Succès":
            # Remplacement de l'erreur NoneType par les données propres
            for key, value in res.items():
                df.at[index, f"{key}{suffix}"] = value
            print(" -> Succès !")
            break 
            
        elif "429" in res['statut']:
            print(f" -> Rate limit atteint. Pause de 6 secondes... (Tentative {attempt + 1}/{max_retries})")
            time.sleep(6)
            
        else:
            # Si le modèle renvoie encore une erreur de strip (NoneType), on la consigne et on avance
            for key, value in res.items():
                df.at[index, f"{key}{suffix}"] = value
            print(f" -> Échec persistant : {res['statut']}")
            break
            
    time.sleep(2)

# --- Recalcul du bilan après correction ---
print(f"\n--- Nouveau Bilan de la reformulation ({suffix.strip('_')}) ---")
nb_total = len(df)
nb_succes = (df[colonne_statut] == "Succès").sum()
nb_echecs = nb_total - nb_succes
ratio_succes = nb_succes / nb_total if nb_total > 0 else 0

print(f"Total des textes traités : {nb_total}")
print(f"Nombre de succès         : {nb_succes}")
print(f"Nombre d'échecs          : {nb_echecs}")
print(f"Ratio de succès          : {ratio_succes:.2f} soit {ratio_succes*100:.2f}%\n")

# Sauvegarde dans ton fichier de benchmark consolidé
df.to_csv("resultats_benchmark_reformulation.csv", index=False, encoding="utf-8")
print("Sauvegarde effectuée dans 'resultats_benchmark_reformulation.csv'")

Reprise des textes en échec pour openai/gpt-oss-20b...
Nouvelle tentative pour le fichier : PAGED/1226498320.txt
 -> Succès !
Nouvelle tentative pour le fichier : PAGED/1479161968.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-4.1.txt
 -> Succès !
Nouvelle tentative pour le fichier : PET/doc-9.5.txt
 -> Succès !

--- Nouveau Bilan de la reformulation (gpt-oss-20b) ---
Total des textes traités : 163
Nombre de succès         : 163
Nombre d'échecs          : 0
Ratio de succès          : 1.00 soit 100.00%

Sauvegarde effectuée dans 'resultats_benchmark_reformulation.csv'

In [13]:
# Dictionnaire d'association des anciens noms vers les nouveaux noms personnalisés
colonnes_a_renommer = {
    'texte_reformule': 'texte_reformule_llama_3_3_70b_instruct',
    'latence_secondes': 'latence_secondes_llama_3_3_70b_instruct',
    'prompt_tokens': 'prompt_tokens_llama_3_3_70b_instruct',
    'completion_tokens': 'completion_tokens_llama_3_3_70b_instruct',
    'total_tokens': 'total_tokens_llama_3_3_70b_instruct',
    'finish_reason': 'finish_reason_llama_3_3_70b_instruct',
    'statut': 'statut_llama_3_3_70b_instruct'
}

# Application du renommage (vérifie d'abord si les colonnes existent pour éviter les erreurs)
df = df.rename(columns={k: v for k, v in colonnes_a_renommer.items() if k in df.columns})

# Affichage de contrôle
print("Métriques renommées avec succès ! Voici la nouvelle liste de vos colonnes :")
print(df.columns.tolist())

Métriques renommées avec succès ! Voici la nouvelle liste de vos colonnes :
['fichier_source', 'texte_original', 'bpmn_genere', 'texte_reformule_llama_3_3_70b_instruct', 'latence_secondes_llama_3_3_70b_instruct', 'prompt_tokens_llama_3_3_70b_instruct', 'completion_tokens_llama_3_3_70b_instruct', 'total_tokens_llama_3_3_70b_instruct', 'finish_reason_llama_3_3_70b_instruct', 'statut_llama_3_3_70b_instruct']

In [47]:
from openai import OpenAI
import pandas as pd
import time

# 1. Initialisation du client avec vos identifiants Nvidia API
client = OpenAI(
  base_url = "https://integrate.api.nvidia.com/v1",
  api_key = "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"
)

# Suffixe utilisé pour la nomenclature des colonnes de ce modèle
suffixe_modele = "_qwen3-coder-480b-a35b-instruct"

# Initialisation des colonnes cibles dans le DataFrame pour éviter les décalages
colonnes_cibles = ['texte_reformule', 'latence_secondes', 'prompt_tokens', 'completion_tokens', 'total_tokens', 'finish_reason', 'statut']
for col in colonnes_cibles:
    df[f"{col}{suffixe_modele}"] = None

# 2. Définition de la fonction de base pour l'appel API (Reformulation inspirée de CoopIS 2024)
def reformulate_process_text(texte_original):
    # Base du prompt de reformulation du papier de Nour Eldin et al. (Figure 4)
    system_prompt = """You are an experienced process owner in a leading company.

Considering the context of Business Process Management (BPM) and process modeling:
- Process: Describes a sequence or flow of activities in an organization.

You are given a possibly incomplete process description delimited by '''. Analyze the description, then reformulate it. Your reformulation should be precise, clear and structured.

Follow these instructions:
- Add all possible termination points.
- Ensure the logical order of steps is clear.
- Use standard, professional terminology.

Here are some examples:
<<
Input: 
'''When a manuscript gets the green light for publication, the editors swing into action. If it passes muster, they give a heads-up to the production and design crews.'''

Output: 
The process begins when a manuscript is approved. The editors then review the manuscript. If the manuscript passes the review, the editors notify the production and design teams. If the manuscript does not pass the review, the process ends.
>>""" 

    user_prompt = f"Process description: ''' {texte_original} '''"

    start_time = time.time()

    try:
        completion = client.chat.completions.create(
            model="qwen/qwen3-coder-480b-a35b-instruct",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,
            top_p=0.7,
            max_tokens=1024,
            stream=False
        )
        
        end_time = time.time()
        
        texte_genere = completion.choices[0].message.content.strip()
        finish_reason = completion.choices[0].finish_reason
        
        prompt_tokens = completion.usage.prompt_tokens if completion.usage else 0
        completion_tokens = completion.usage.completion_tokens if completion.usage else 0
        total_tokens = completion.usage.total_tokens if completion.usage else 0
        
        return {
            "texte_reformule": texte_genere,
            "latence_secondes": round(end_time - start_time, 2),
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens,
            "finish_reason": finish_reason,
            "statut": "Succès"
        }
        
    except Exception as e:
        end_time = time.time()
        return {
            "texte_reformule": None,
            "latence_secondes": round(end_time - start_time, 2),
            "prompt_tokens": None,
            "completion_tokens": None,
            "total_tokens": None,
            "finish_reason": None,
            "statut": f"Erreur: {str(e)}"
        }

# 3. Boucle d'exécution principale avec gestion intégrée des retries (Erreurs 429)
print("Début de la reformulation et du benchmarking avec qwen/qwen3-coder-480b-a35b-instruct...")

for index, row in df.iterrows():
    print(f"Traitement {index + 1}/{len(df)} : {row['fichier_source']}")
    
    max_retries = 3
    for attempt in range(max_retries):
        res = reformulate_process_text(row['texte_original'])
        
        if res['statut'] == "Succès":
            # Enregistrement direct dans les colonnes renommées selon le modèle
            for key, value in res.items():
                df.at[index, f"{key}{suffixe_modele}"] = value
            break
            
        elif "429" in res['statut']:
            # Si le Rate Limit est atteint, on patiente 6 secondes comme demandé avant la prochaine tentative
            print(f"  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative {attempt + 1}/{max_retries})")
            time.sleep(6)
            
        else:
            # En cas d'autre erreur critique, on enregistre le message d'erreur et on passe à la suite
            print(f"  -> Abandon suite à une erreur : {res['statut']}")
            for key, value in res.items():
                df.at[index, f"{key}{suffixe_modele}"] = value
            break
            
    # Pause préventive de 2 secondes à la fin de chaque ligne pour stabiliser les requêtes
    time.sleep(2)

print("\nTraitement global terminé avec succès !")

# 4. Affichage d'un bilan rapide des performances observées
nb_total = len(df)
nb_succes = (df[f'statut{suffixe_modele}'] == "Succès").sum()
ratio_succes = nb_succes / nb_total if nb_total > 0 else 0

print("\n--- BILAN DE L'EXÉCUTION ---")
print(f"Total des textes traités : {nb_total}")
print(f"Nombre de succès         : {nb_succes} ({ratio_succes*100:.2f}%)")
print(f"Latence moyenne          : {df[f'latence_secondes{suffixe_modele}'].mean():.2f} secondes")
print(f"Moyenne tokens générés   : {df[f'completion_tokens{suffixe_modele}'].mean():.0f}")

# Sauvegarde automatique au format CSV
df.to_csv("resultats_benchmark_reformulation.csv", index=False, encoding="utf-8")
print("\nDataFrame sauvegardé sous le nom 'resultats_benchmark_reformulation.csv'")

Début de la reformulation et du benchmarking avec qwen/qwen3-coder-480b-a35b-instruct...
Traitement 1/163 : PAGED/1934621887.txt
Traitement 2/163 : PAGED/1329958954.txt
Traitement 3/163 : PAGED/1235925705.txt
Traitement 4/163 : PAGED/1352840228.txt
Traitement 5/163 : PAGED/1286652977.txt
Traitement 6/163 : PAGED/1226498320.txt
Traitement 7/163 : PAGED/1473806539.txt
Traitement 8/163 : PAGED/1337645986.txt
Traitement 9/163 : PAGED/1409572751.txt
Traitement 10/163 : PAGED/1940833472.txt
Traitement 11/163 : PAGED/1309672350.txt
Traitement 12/163 : PAGED/1233431981.txt
Traitement 13/163 : PAGED/1410268331.txt
Traitement 14/163 : PAGED/1191144576.txt
Traitement 15/163 : PAGED/1195286382.txt
Traitement 16/163 : PAGED/1241042198.txt
Traitement 17/163 : PAGED/1467107206.txt
Traitement 18/163 : PAGED/1425006907.txt
Traitement 19/163 : PAGED/1283995127.txt
Traitement 20/163 : PAGED/1467836466.txt
Traitement 21/163 : PAGED/1247939176.txt
Traitement 22/163 : PAGED/1383686290.txt
Traitement 23/163 : PAGED/1900639740.txt
Traitement 24/163 : PAGED/1900538815.txt
Traitement 25/163 : PAGED/1290321174.txt
Traitement 26/163 : PAGED/1361468541.txt
Traitement 27/163 : PAGED/1314718328.txt
Traitement 28/163 : PAGED/1468373358.txt
Traitement 29/163 : PAGED/1907085906.txt
Traitement 30/163 : PAGED/1228639130.txt
Traitement 31/163 : PAGED/1904148439.txt
Traitement 32/163 : PAGED/1226133062.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 2/3)
Traitement 33/163 : PAGED/1188157819.txt
Traitement 34/163 : PAGED/1376709591.txt
Traitement 35/163 : PAGED/1429084667.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 36/163 : PAGED/1339604510.txt
Traitement 37/163 : PAGED/1288790214.txt
Traitement 38/163 : PAGED/1381696062.txt
Traitement 39/163 : PAGED/1479161968.txt
Traitement 40/163 : PAGED/1414026620.txt
Traitement 41/163 : PAGED/1192409168.txt
Traitement 42/163 : PAGED/1299931035.txt
Traitement 43/163 : PAGED/1237501896.txt
Traitement 44/163 : PAGED/1340845012.txt
Traitement 45/163 : PAGED/1263880376.txt
Traitement 46/163 : MaD/churn_rate_prevention_process_churn_rate_prevention_process_55.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 47/163 : MaD/employee_onboarding_process_employee_onboarding_process_185.txt
Traitement 48/163 : MaD/final_grades_submission_process_final grades submission process_172.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 49/163 : MaD/churn_rate_prevention_process_churn_rate_prevention_process_102.txt
Traitement 50/163 : MaD/process_for_optimizing_a_process_process_for_optimizing_a_process_70.txt
Traitement 51/163 : MaD/content_promotion_process_content_promotion_process_77.txt
Traitement 52/163 : MaD/accounts_receivable_process_accounts_receivable_process_135.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 53/163 : MaD/accounts_receivable_process_accounts_receivable_process_122.txt
Traitement 54/163 : MaD/startup_due_diligence_for_a_venture_capitalist_startup_due_diligence_for_a_venture_capitalist_86.txt
Traitement 55/163 : MaD/customer_support_process_for_the_ticket_management_customer_support_process_for_the_ticket_management_76.txt
Traitement 56/163 : MaD/client_onboarding_process_for_a_marketing_agency_client_onboarding_process_for_a_marketing_agency_170.txt
Traitement 57/163 : MaD/startup_due_diligence_for_a_venture_capitalist_startup_due_diligence_for_a_venture_capitalist_145.txt
Traitement 58/163 : MaD/order_fulfillment_process_order_fulfillment_process_118.txt
Traitement 59/163 : MaD/account_payable_process_account_payable_process_117.txt
Traitement 60/163 : MaD/final_grades_submission_process_final grades submission process_38.txt
Traitement 61/163 : MaD/customer_support_process_for_the_ticket_management_customer_support_process_for_the_ticket_management_108.txt
Traitement 62/163 : MaD/churn_rate_prevention_process_churn_rate_prevention_process_35.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 2/3)
Traitement 63/163 : MaD/final_grades_submission_process_final grades submission process_107.txt
Traitement 64/163 : MaD/budget_preparation_process_budget_preparation_process_189.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 65/163 : MaD/employee_onboarding_process_employee_onboarding_process_104.txt
Traitement 66/163 : MaD/account_payable_process_account_payable_process_44.txt
Traitement 67/163 : MaD/project_management_process_project_management_process_95.txt
Traitement 68/163 : MaD/startup_due_diligence_for_a_venture_capitalist_startup_due_diligence_for_a_venture_capitalist_65.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 69/163 : MaD/loan_application_process_loan_application_process_97.txt
Traitement 70/163 : MaD/employee_onboarding_process_employee_onboarding_process_113.txt
Traitement 71/163 : MaD/order_fulfillment_process_order_fulfillment_process_106.txt
Traitement 72/163 : MaD/process_for_optimizing_a_process_process_for_optimizing_a_process_4.txt
Traitement 73/163 : MaD/client_onboarding_process_for_a_marketing_agency_client_onboarding_process_for_a_marketing_agency_61.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 2/3)
Traitement 74/163 : MaD/loan_application_process_loan_application_process_45.txt
Traitement 75/163 : MaD/content_promotion_process_content_promotion_process_103.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 2/3)
Traitement 76/163 : MaD/purchase_order_workflow_purchase_order_workflow_158.txt
Traitement 77/163 : MaD/accounts_receivable_process_accounts_receivable_process_48.txt
Traitement 78/163 : MaD/budget_preparation_process_budget_preparation_process_143.txt
Traitement 79/163 : MaD/account_payable_process_account_payable_process_126.txt
Traitement 80/163 : MaD/project_management_process_project_management_process_85.txt
Traitement 81/163 : MaD/process_for_optimizing_a_process_process_for_optimizing_a_process_21.txt
Traitement 82/163 : MaD/budget_preparation_process_budget_preparation_process_195.txt
Traitement 83/163 : MaD/client_onboarding_process_for_a_marketing_agency_client_onboarding_process_for_a_marketing_agency_10.txt
Traitement 84/163 : MaD/purchase_order_workflow_purchase_order_workflow_9.txt
Traitement 85/163 : MaD/customer_support_process_for_the_ticket_management_customer_support_process_for_the_ticket_management_161.txt
Traitement 86/163 : MaD/order_fulfillment_process_order_fulfillment_process_0.txt
Traitement 87/163 : MaD/content_promotion_process_content_promotion_process_165.txt
Traitement 88/163 : MaD/project_management_process_project_management_process_33.txt
Traitement 89/163 : MaD/purchase_order_workflow_purchase_order_workflow_111.txt
Traitement 90/163 : MaD/loan_application_process_loan_application_process_30.txt
Traitement 91/163 : PET/doc-5.2.txt
Traitement 92/163 : PET/doc-3.5.txt
Traitement 93/163 : PET/doc-5.3.txt
Traitement 94/163 : PET/doc-7.1.txt
Traitement 95/163 : PET/doc-5.1.txt
Traitement 96/163 : PET/doc-3.7.txt
Traitement 97/163 : PET/doc-1.4.txt
Traitement 98/163 : PET/doc-3.6.txt
Traitement 99/163 : PET/doc-5.4.txt
Traitement 100/163 : PET/doc-3.2.txt
Traitement 101/163 : PET/doc-1.1.txt
Traitement 102/163 : PET/doc-3.3.txt
Traitement 103/163 : PET/doc-3.1.txt
Traitement 104/163 : PET/doc-1.3.txt
Traitement 105/163 : PET/doc-1.2.txt
Traitement 106/163 : PET/doc-10.4.txt
Traitement 107/163 : PET/doc-4.1.txt
Traitement 108/163 : PET/doc-6.3.txt
Traitement 109/163 : PET/doc-6.2.txt
Traitement 110/163 : PET/doc-10.5.txt
Traitement 111/163 : PET/doc-10.7.txt
Traitement 112/163 : PET/doc-6.1.txt
Traitement 113/163 : PET/doc-10.6.txt
Traitement 114/163 : PET/doc-10.2.txt
Traitement 115/163 : PET/doc-2.1.txt
Traitement 116/163 : PET/doc-6.4.txt
Traitement 117/163 : PET/doc-10.3.txt
Traitement 118/163 : PET/doc-10.1.txt
Traitement 119/163 : PET/doc-2.2.txt
Traitement 120/163 : PET/doc-8.3.txt
Traitement 121/163 : PET/doc-8.2.txt
Traitement 122/163 : PET/doc-10.8.txt
Traitement 123/163 : PET/doc-8.1.txt
Traitement 124/163 : PET/doc-10.9.txt
Traitement 125/163 : PET/doc-10.12.txt
Traitement 126/163 : PET/doc-10.13.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 127/163 : PET/doc-9.5.txt
Traitement 128/163 : PET/doc-10.11.txt
Traitement 129/163 : PET/doc-10.10.txt
Traitement 130/163 : PET/doc-9.4.txt
Traitement 131/163 : PET/doc-10.14.txt
Traitement 132/163 : PET/doc-9.1.txt
Traitement 133/163 : PET/doc-9.3.txt
Traitement 134/163 : PET/doc-3.8.txt
Traitement 135/163 : PET/doc-9.2.txt
Traitement 136/163 : Text_and_BPMN_Zenodo/G_g03.txt
Traitement 137/163 : Text_and_BPMN_Zenodo/G_g01.txt
Traitement 138/163 : Text_and_BPMN_Zenodo/R_g01.txt
Traitement 139/163 : Text_and_BPMN_Zenodo/M_g02.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 140/163 : Text_and_BPMN_Zenodo/X_g03.txt
Traitement 141/163 : Text_and_BPMN_Zenodo/M_g01.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 2/3)
Traitement 142/163 : Text_and_BPMN_Zenodo/X_g01.txt
Traitement 143/163 : Text_and_BPMN_Zenodo/R_j03.txt
Traitement 144/163 : Text_and_BPMN_Zenodo/R_j02.txt
Traitement 145/163 : Text_and_BPMN_Zenodo/G_j01.txt
Traitement 146/163 : Text_and_BPMN_Zenodo/R_j01.txt
Traitement 147/163 : Text_and_BPMN_Zenodo/R_j04.txt
Traitement 148/163 : Text_and_BPMN_Zenodo/M_k05.txt
Traitement 149/163 : Text_and_BPMN_Zenodo/V_k08.txt
Traitement 150/163 : Text_and_BPMN_Zenodo/E_j05.txt
Traitement 151/163 : Text_and_BPMN_Zenodo/M_j03.txt
Traitement 152/163 : Text_and_BPMN_Zenodo/M_j02.txt
Traitement 153/163 : Text_and_BPMN_Zenodo/E_j04.txt
Traitement 154/163 : Text_and_BPMN_Zenodo/V_k09.txt
Traitement 155/163 : Text_and_BPMN_Zenodo/M_j01.txt
Traitement 156/163 : Text_and_BPMN_Zenodo/E_j03.txt
Traitement 157/163 : Text_and_BPMN_Zenodo/E_j02.txt
Traitement 158/163 : Text_and_BPMN_Zenodo/E_j01.txt
  -> Code 429 (Too Many Requests). Pause de 6 secondes... (Tentative 1/3)
Traitement 159/163 : Text_and_BPMN_Zenodo/V_g01.txt
Traitement 160/163 : Camunda_BPMN4Research/EN_Ex4.txt
Traitement 161/163 : Camunda_BPMN4Research/EN_Ex3.txt
Traitement 162/163 : Camunda_BPMN4Research/EN_Ex2.txt
Traitement 163/163 : Camunda_BPMN4Research/EN_Ex1.txt

Traitement global terminé avec succès !

--- BILAN DE L'EXÉCUTION ---
Total des textes traités : 163
Nombre de succès         : 163 (100.00%)
Latence moyenne          : 11.98 secondes
Moyenne tokens générés   : 286

DataFrame sauvegardé sous le nom 'resultats_benchmark_reformulation.csv'

In [21]:
df

,fichier_source,texte_original,bpmn_genere,texte_reformule_llama_3_3_70b_instruct,latence_secondes_llama_3_3_70b_instruct,prompt_tokens_llama_3_3_70b_instruct,completion_tokens_llama_3_3_70b_instruct,total_tokens_llama_3_3_70b_instruct,finish_reason_llama_3_3_70b_instruct,statut_llama_3_3_70b_instruct,...,total_tokens_llama-3.1-8b-instruct,finish_reason_llama-3.1-8b-instruct,statut_llama-3.1-8b-instruct,texte_reformule_mistral-small-4-119b-2603,latence_secondes_mistral-small-4-119b-2603,prompt_tokens_mistral-small-4-119b-2603,completion_tokens_mistral-small-4-119b-2603,total_tokens_mistral-small-4-119b-2603,finish_reason_mistral-small-4-119b-2603,statut_mistral-small-4-119b-2603
0,PAGED/1934621887.txt,"For Personal Users: To begin, send a request f...",None,The process begins when a request for account ...,14.99,507.0,491.0,998.0,stop,Succès,...,1152,stop,Succès,### **Process: Account Creation and Verificati...,8.21,493,539,1032,stop,Succès
1,PAGED/1329958954.txt,"To start the Meeting Scheduler process, begin ...",None,The Meeting Scheduler process begins when a me...,9.61,264.0,176.0,440.0,stop,Succès,...,376,stop,Succès,**Reformulated Process Description:**\n\n**Pro...,3.47,250,229,479,stop,Succès
2,PAGED/1235925705.txt,"To begin the process, the Resupply Cycle is tr...",None,The process begins when the Resupply Cycle is ...,13.11,401.0,324.0,725.0,stop,Succès,...,660,stop,Succès,### **Reformulated Process Description: Resupp...,9.5,391,559,950,stop,Succès
3,PAGED/1352840228.txt,"To begin the process for ACME Company, you sho...",None,The process for ACME Company begins when the r...,16.69,493.0,394.0,887.0,stop,Succès,...,908,stop,Succès,### **Reformulated Process Description: ACME C...,6.42,477,330,807,stop,Succès
4,PAGED/1286652977.txt,"In the beginning, a loan request is created an...",None,The process begins when a loan request is crea...,7.31,382.0,255.0,637.0,stop,Succès,...,597,stop,Succès,**Reformulated Process Description:**\n\n**Pro...,6.85,371,363,734,stop,Succès
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Text_and_BPMN_Zenodo/V_g01.txt,Category: Vending and Shipping\nTitle: Robotic...,None,The process begins when the robotic burger sel...,37.96,386.0,314.0,700.0,stop,Succès,...,749,stop,Succès,**Process: Robotic Burger Seller Order Fulfill...,10.29,377,474,851,stop,Succès
159,Camunda_BPMN4Research/EN_Ex4.txt,Background \nA self-service restaurant is unde...,None,The optimized process for the self-service res...,5.63,586.0,405.0,991.0,stop,Succès,...,1288,stop,Succès,### **Optimized Process Model for Self-Service...,10.43,572,665,1237,stop,Succès
160,Camunda_BPMN4Research/EN_Ex3.txt,Background \nA credit protection agency (in Ge...,None,The process begins when a sales clerk in a ban...,8.97,524.0,459.0,983.0,stop,Succès,...,1041,stop,Succès,### **Reformulated Process Description**\n\n##...,11.65,508,597,1105,stop,Succès
161,Camunda_BPMN4Research/EN_Ex2.txt,Please model the following process: \nIf an i...,None,The process begins when a potential subrogatio...,22.08,421.0,339.0,760.0,stop,Succès,...,768,stop,Succès,**Process: Handling Insurance Subrogation Case...,5.78,407,336,743,stop,Succès
162,Camunda_BPMN4Research/EN_Ex1.txt,Please model the following process \nIf goods...,None,The process begins when a decision is made to ...,14.04,379.0,298.0,677.0,stop,Succès,...,608,stop,Succès,**Process Name:** Goods Shipment Process\n\n**...,12.52,366,610,976,stop,Succès

In [51]:
import pandas as pd
import time
from openai import OpenAI

# 1. Initialisation du client API
client = OpenAI(
  base_url = "https://integrate.api.nvidia.com/v1",
  api_key = "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" 
)

# 2. Création du dataset de test (on isole la première ligne du dataframe complet)
# Vous pouvez changer head(1) par sample(1) si vous voulez une ligne au hasard
triplet_test_df = df.head(1).copy()

# 3. Définition de la fonction d'extraction Zéro-Shot
def extract_triplets_spo(texte_reformule):
    # Sécurité : si la reformulation avait échoué (None ou vide)
    if pd.isna(texte_reformule) or not str(texte_reformule).strip():
        return "Aucun texte à analyser"

    system_prompt = """You are an expert in Process Mining and Natural Language Processing.
Your task is to extract process knowledge from a standardized process description and convert it into structured "Facts".

DEFINITION OF A FACT:
A fact is strictly a Subject-Predicate-Object (SPO) triplet that represents a single action or state in the process.
- Subject: The actor, role, or system performing the action.
- Predicate: The specific action verb (keep it concise).
- Object: The item, document, or entity being acted upon.
Format: (Subject, Predicate, Object)

HANDLING GATEWAYS AND BRANCHES (CRITICAL RULE):
The process description may contain decision points or conditional logic. You must NOT try to model complex logical gateways. 
Instead, you must extract complete, independent execution paths called "Scenarios". 
Whenever a decision point splits the process, you must create separate Scenarios to represent each possible outcome. A scenario traces a sequence of facts from the split point down to a specific termination point.

INSTRUCTIONS:
1. Carefully analyze the provided process description.
2. Identify all actions and the conditions that trigger them.
3. Group the extracted SPO facts into logical Scenarios. 
4. Ensure the chronological order of facts within each scenario is strictly respected.
5. Output ONLY the scenarios and their facts. Do not add conversational filler.

EXPECTED OUTPUT FORMAT:
Scenario 1: [Name of the base path or condition]
1. (Subject, Predicate, Object)
2. (Subject, Predicate, Object)

Scenario 2: [Name of the alternative path]
1. (Subject, Predicate, Object)"""

    user_prompt = f"INPUT PROCESS DESCRIPTION:\n''' {texte_reformule} '''"

    try:
        completion = client.chat.completions.create(
            model="meta/llama-3.3-70b-instruct", # Le "Juge" extracteur
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.1, # Température très basse pour un formatage strict
            top_p=0.7,
            max_tokens=1024,
            stream=False
        )
        return completion.choices[0].message.content.strip()
    except Exception as e:
        return f"Erreur d'extraction : {str(e)}"

# 4. Identification automatique de toutes vos colonnes de reformulation
# On cherche toutes les colonnes qui commencent par "texte_reformule_"
colonnes_reformulees = [col for col in triplet_test_df.columns if col.startswith("texte_reformule_")]

print(f"Début de l'extraction des triplets sur 1 échantillon ({len(colonnes_reformulees)} modèles détectés)...\n")

# 5. Boucle d'extraction
for col_source in colonnes_reformulees:
    print(f"Traitement de la source : {col_source}")
    
    # Création du nouveau nom de colonne selon votre convention
    nom_colonne_extraction = f"{col_source}_extr_llama_3_3_70b"
    
    # On initialise la colonne
    triplet_test_df[nom_colonne_extraction] = None
    
    # Extraction pour la ligne isolée
    texte = triplet_test_df.at[triplet_test_df.index[0], col_source]
    resultat_spo = extract_triplets_spo(texte)
    
    # Enregistrement
    triplet_test_df.at[triplet_test_df.index[0], nom_colonne_extraction] = resultat_spo
    
    # Pause préventive de 2 secondes
    time.sleep(2)

print("\nExtraction terminée avec succès !")

# 6. Affichage brut des résultats générés pour comparer
colonnes_extraites = [col for col in triplet_test_df.columns if "_extr_llama_3_3_70b" in col]

print("\n" + "="*60)
print("COMPARAISON DES EXTRACTIONS PAR MODÈLE SOURCE")
print("="*60)

for col_resultat in colonnes_extraites:
    print(f"\n▶️ RÉSULTAT POUR : {col_resultat}")
    print("-" * 60)
    print(triplet_test_df[col_resultat].iloc[0])
    print("-" * 60)

Début de l'extraction des triplets sur 1 échantillon (11 modèles détectés)...

Traitement de la source : texte_reformule_llama_3_3_70b_instruct
Traitement de la source : texte_reformule_llama-3.2-3b-instruct
Traitement de la source : texte_reformule_llama-3.1-8b-instruct
Traitement de la source : texte_reformule_mistral-small-4-119b-2603
Traitement de la source : texte_reformule_ministral-14b-instruct-2512
Traitement de la source : texte_reformule_mistral-nemotron
Traitement de la source : texte_reformule_gpt-oss-20b
Traitement de la source : texte_reformule_gpt-oss-120b
Traitement de la source : texte_reformule_kimi-k2.6
Traitement de la source : texte_reformule_nvidia-nemotron-nano-9b-v2
Traitement de la source : texte_reformule_qwen3-coder-480b-a35b-instruct

Extraction terminée avec succès !

============================================================
COMPARAISON DES EXTRACTIONS PAR MODÈLE SOURCE
============================================================

▶️ RÉSULTAT POUR : texte_reformule_llama_3_3_70b_instruct_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Personal User - Successful Account Creation
1. (System, Prompts, User to select country)
2. (System, Requests, Additional user information)
3. (User, Enters, Business details)
4. (User, Enters, Credit card details)
5. (System, Prompts, Account verification)
6. (User, Verifies, Account)
7. (User, Creates, Password)

Scenario 2: Personal User - Failed Account Creation
1. (System, Prompts, User to select country)
2. (System, Requests, Additional user information)
3. (User, Enters, Business details)
4. (User, Enters, Credit card details)
5. (System, Prompts, Account verification)
6. (User, Fails, Account verification)
7. (System, Generates, Error notification)

Scenario 3: Personal User - Failed Business Details Entry
1. (System, Prompts, User to select country)
2. (System, Requests, Additional user information)
3. (User, Fails, Business details entry)
4. (System, Generates, Error notification)

Scenario 4: Personal User - Failed Credit Card Details Entry
1. (System, Prompts, User to select country)
2. (System, Requests, Additional user information)
3. (User, Enters, Business details)
4. (User, Fails, Credit card details entry)
5. (System, Generates, Error notification)

Scenario 5: PayPal System - Country Not Accepted
1. (System, Receives, Request)
2. (System, Gathers, Country information)
3. (System, Checks, Country acceptance)
4. (System, Generates, Error message)

Scenario 6: PayPal System - Successful Account Creation
1. (System, Receives, Request)
2. (System, Gathers, Country information)
3. (System, Checks, Country acceptance)
4. (System, Requests, Personal information)
5. (System, Requests, Business details)
6. (System, Checks, Business details acceptance)
7. (System, Requests, Card details)
8. (System, Checks, Card details acceptance)
9. (System, Sends, Verification email)
10. (System, Checks, Verification acceptance)
11. (System, Requests, Password creation)
12. (User, Creates, Password)

Scenario 7: PayPal System - Business Details Not Accepted
1. (System, Receives, Request)
2. (System, Gathers, Country information)
3. (System, Checks, Country acceptance)
4. (System, Requests, Personal information)
5. (System, Requests, Business details)
6. (System, Checks, Business details acceptance)
7. (System, Generates, Error notification)

Scenario 8: PayPal System - Card Details Not Accepted
1. (System, Receives, Request)
2. (System, Gathers, Country information)
3. (System, Checks, Country acceptance)
4. (System, Requests, Personal information)
5. (System, Requests, Business details)
6. (System, Checks, Business details acceptance)
7. (System, Requests, Card details)
8. (System, Checks, Card details acceptance)
9. (System, Generates, Error notification)

Scenario 9: PayPal System - Verification Not Accepted
1. (System, Receives, Request)
2. (System, Gathers, Country information)
3. (System, Checks, Country acceptance)
4. (System, Requests, Personal information)
5. (System, Requests, Business details)
6. (System, Checks, Business details acceptance)
7. (System, Requests, Card details)
8. (System, Checks, Card details acceptance)
9. (System, Sends, Verification email)
10. (System, Checks, Verification acceptance)
11. (System, Generates, Error notification)
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_llama-3.2-3b-instruct_extr_llama_3_3_70b
------------------------------------------------------------
Aucun texte à analyser
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_llama-3.1-8b-instruct_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Successful Account Creation
1. (Personal User, sends, account creation request)
2. (Personal User, selects, country)
3. (System, sends, information request)
4. (Personal User, enters, business details)
5. (Personal User, enters, credit card details)
6. (System, verifies, account)
7. (Personal User, enters, password)

Scenario 2: Country Not Accepted
1. (Personal User, sends, account creation request)
2. (Personal User, selects, country)
3. (PayPal System, gathers, country information)
4. (PayPal System, analyzes, country information)
5. (PayPal System, ends process with, error message)

Scenario 3: Business Details Not Accepted
1. (Personal User, sends, account creation request)
2. (Personal User, selects, country)
3. (System, sends, information request)
4. (Personal User, enters, business details)
5. (PayPal System, receives, business details)
6. (PayPal System, analyzes, business details)
7. (PayPal System, ends process with, error notification)

Scenario 4: Card Details Not Accepted
1. (Personal User, sends, account creation request)
2. (Personal User, selects, country)
3. (System, sends, information request)
4. (Personal User, enters, business details)
5. (Personal User, enters, credit card details)
6. (PayPal System, checks, card details)
7. (PayPal System, ends process with, error notification)

Scenario 5: Verification Not Accepted
1. (Personal User, sends, account creation request)
2. (Personal User, selects, country)
3. (System, sends, information request)
4. (Personal User, enters, business details)
5. (Personal User, enters, credit card details)
6. (System, verifies, account)
7. (PayPal System, sends, verification email)
8. (PayPal System, checks, verification)
9. (PayPal System, ends process with, error notification)
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_mistral-small-4-119b-2603_extr_llama_3_3_70b
------------------------------------------------------------
Erreur d'extraction : Error code: 429 - {'status': 429, 'title': 'Too Many Requests'}
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_ministral-14b-instruct-2512_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Successful Account Creation
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Enters, Credit Card Details)
6. (User, Completes, Account Verification)
7. (User, Sets, Secure Password)
8. (System, Activates, Account)
9. (System, Sends, Confirmation Email)

Scenario 2: Country Selection Failure
1. (User, Submits, Account Creation Request)
2. (User, Fails, Country Selection)
3. (System, Generates, Error Notification)

Scenario 3: Business Details Entry Failure
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Fails, Business Details Entry)
5. (System, Generates, Error Notification)

Scenario 4: Credit Card Details Entry Failure
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Fails, Credit Card Details Entry)
6. (System, Generates, Error Notification)

Scenario 5: Account Verification Failure
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Enters, Credit Card Details)
6. (User, Fails, Account Verification)
7. (System, Generates, Error Notification)

Scenario 6: Password Setup Failure
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Enters, Credit Card Details)
6. (User, Completes, Account Verification)
7. (User, Fails, Password Setup)
8. (System, Prompts, Password Retry)

Scenario 7: Country Not Supported by PayPal
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Checks, Country Support)
4. (System, Generates, Error Notification)

Scenario 8: Incomplete Business Information
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Incomplete Business Details)
5. (System, Generates, Error Notification)

Scenario 9: Invalid Card Details
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Enters, Invalid Card Details)
6. (System, Generates, Error Notification)

Scenario 10: Verification Failure
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Enters, Credit Card Details)
6. (User, Fails, Verification)
7. (System, Generates, Error Notification)

Scenario 11: Password Does Not Meet Security Standards
1. (User, Submits, Account Creation Request)
2. (User, Selects, Country)
3. (System, Prompts, Information Request)
4. (User, Provides, Business Details)
5. (User, Enters, Credit Card Details)
6. (User, Completes, Account Verification)
7. (User, Sets, Insecure Password)
8. (System, Prompts, Password Retry)
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_mistral-nemotron_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Successful Account Creation for Personal User
1. (Personal User, sends, request for account creation)
2. (Personal User, selects, country)
3. (System, requests, additional information)
4. (Personal User, enters, business details)
5. (Personal User, enters, credit card details)
6. (System, verifies, account)
7. (Personal User, enters, password)

Scenario 2: Failed Account Creation for Personal User - Verification Failure
1. (Personal User, sends, request for account creation)
2. (Personal User, selects, country)
3. (System, requests, additional information)
4. (Personal User, enters, business details)
5. (Personal User, enters, credit card details)
6. (System, verifies, account)
7. (System, generates, error notification)

Scenario 3: Successful Account Creation for PayPal System
1. (PayPal System, receives, request for account creation)
2. (PayPal System, gathers, country information)
3. (PayPal System, requests, personal information)
4. (PayPal System, analyzes, business details)
5. (PayPal System, requests, credit card details)
6. (PayPal System, sends, verification email)
7. (PayPal System, requests, password)
8. (Personal User, enters, password)

Scenario 4: Failed Account Creation for PayPal System - Country Not Accepted
1. (PayPal System, receives, request for account creation)
2. (PayPal System, gathers, country information)
3. (PayPal System, generates, error message)

Scenario 5: Failed Account Creation for PayPal System - Business Details Not Accepted
1. (PayPal System, receives, request for account creation)
2. (PayPal System, gathers, country information)
3. (PayPal System, requests, personal information)
4. (PayPal System, analyzes, business details)
5. (PayPal System, generates, error notification)

Scenario 6: Failed Account Creation for PayPal System - Card Details Not Accepted
1. (PayPal System, receives, request for account creation)
2. (PayPal System, gathers, country information)
3. (PayPal System, requests, personal information)
4. (PayPal System, analyzes, business details)
5. (PayPal System, requests, credit card details)
6. (PayPal System, generates, error notification)

Scenario 7: Failed Account Creation for PayPal System - Verification Not Accepted
1. (PayPal System, receives, request for account creation)
2. (PayPal System, gathers, country information)
3. (PayPal System, requests, personal information)
4. (PayPal System, analyzes, business details)
5. (PayPal System, requests, credit card details)
6. (PayPal System, sends, verification email)
7. (PayPal System, generates, error notification)
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_gpt-oss-20b_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Successful Account Creation
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Selects, Country)
4. (System, Requests, Information)
5. (User, Enters, Business Details)
6. (User, Enters, Credit-Card Details)
7. (System, Verifies, Account)
8. (User, Enters, Password)
9. (System, Completes, Account Creation)

Scenario 2: Request Submission Failed
1. (User, Initiates, Account-Creation Request)
2. (User, Fails to Submit, Account-Creation Request)

Scenario 3: Country Selection Cancelled
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Fails to Select, Country)

Scenario 4: Information Request Not Received
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Selects, Country)
4. (System, Fails to Request, Information)

Scenario 5: Business Details Invalid
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Selects, Country)
4. (System, Requests, Information)
5. (User, Enters, Invalid Business Details)

Scenario 6: Credit-Card Rejected
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Selects, Country)
4. (System, Requests, Information)
5. (User, Enters, Business Details)
6. (User, Enters, Rejected Credit-Card Details)

Scenario 7: Account Verification Failed
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Selects, Country)
4. (System, Requests, Information)
5. (User, Enters, Business Details)
6. (User, Enters, Credit-Card Details)
7. (System, Fails to Verify, Account)

Scenario 8: Password Entry Failed
1. (User, Initiates, Account-Creation Request)
2. (User, Submits, Account-Creation Request)
3. (User, Selects, Country)
4. (System, Requests, Information)
5. (User, Enters, Business Details)
6. (User, Enters, Credit-Card Details)
7. (System, Verifies, Account)
8. (User, Fails to Enter, Password)
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_gpt-oss-120b_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Successful Account Creation
1. (User, Initiates, Account-Creation Request)
2. (User, Selects, Country)
3. (System, Generates, Information-Request)
4. (System, Sends, Information Request)
5. (User, Enters, Business Details)
6. (User, Enters, Credit-Card Details)
7. (System, Verifies, Account)
8. (User, Creates, Password)
9. (System, Collects, Country Information)
10. (System, Performs, Country Acceptance Check)
11. (System, Requests, Personal Information)
12. (System, Receives, Business Details)
13. (System, Performs, Business-Details Acceptance Check)
14. (System, Requests, Credit-Card Details)
15. (System, Performs, Card-Details Acceptance Check)
16. (System, Sends, Verification Email)
17. (System, Performs, Verification Acceptance Check)
18. (System, Requests, Password)

Scenario 2: Verification Failure
1. (User, Initiates, Account-Creation Request)
2. (User, Selects, Country)
3. (System, Generates, Information-Request)
4. (System, Sends, Information Request)
5. (User, Enters, Business Details)
6. (User, Enters, Credit-Card Details)
7. (System, Verifies, Account)
8. (System, Terminates, Account Creation)
9. (System, Collects, Country Information)
10. (System, Performs, Country Acceptance Check)
11. (System, Requests, Personal Information)
12. (System, Receives, Business Details)
13. (System, Performs, Business-Details Acceptance Check)
14. (System, Requests, Credit-Card Details)
15. (System, Performs, Card-Details Acceptance Check)

Scenario 3: Country Not Accepted
1. (User, Initiates, Account-Creation Request)
2. (User, Selects, Country)
3. (System, Collects, Country Information)
4. (System, Performs, Country Acceptance Check)
5. (System, Terminates, Account Creation)

Scenario 4: Business Details Not Accepted
1. (User, Initiates, Account-Creation Request)
2. (User, Selects, Country)
3. (System, Collects, Country Information)
4. (System, Performs, Country Acceptance Check)
5. (System, Requests, Personal Information)
6. (System, Receives, Business Details)
7. (System, Performs, Business-Details Acceptance Check)
8. (System, Terminates, Account Creation)
9. (User, Enters, Business Details)

Scenario 5: Card Details Not Accepted
1. (User, Initiates, Account-Creation Request)
2. (User, Selects, Country)
3. (System, Collects, Country Information)
4. (System, Performs, Country Acceptance Check)
5. (System, Requests, Personal Information)
6. (System, Receives, Business Details)
7. (System, Performs, Business-Details Acceptance Check)
8. (System, Requests, Credit-Card Details)
9. (System, Performs, Card-Details Acceptance Check)
10. (System, Terminates, Account Creation)
11. (User, Enters, Credit-Card Details)

Scenario 6: Verification Not Accepted
1. (User, Initiates, Account-Creation Request)
2. (User, Selects, Country)
3. (System, Collects, Country Information)
4. (System, Performs, Country Acceptance Check)
5. (System, Requests, Personal Information)
6. (System, Receives, Business Details)
7. (System, Performs, Business-Details Acceptance Check)
8. (System, Requests, Credit-Card Details)
9. (System, Performs, Card-Details Acceptance Check)
10. (System, Sends, Verification Email)
11. (System, Performs, Verification Acceptance Check)
12. (System, Terminates, Account Creation)
------------------------------------------------------------

▶️ RÉSULTAT POUR : texte_reformule_kimi-k2.6_extr_llama_3_3_70b
------------------------------------------------------------
Scenario 1: Successful Account Creation
1. (Personal User, Submits, Account Creation Request)
2. (Personal User, Selects, Country)
3. (Personal User, Receives, Information Request)
4. (Personal User, Enters, Business Details)
5. (Personal User, Enters, Credit Card Details)
6. (Personal User, Verifies, Account)
7. (Personal User, Enters, Password)
8. (PayPal System, Receives, Account Creation Request)
9. (PayPal System, Gathers, Country Information)
10. (PayPal System, Evaluates, Country)
11. (PayPal System, Requests, Personal Information)
12. (PayPal System, Receives, Business Details)
13. (PayPal System, Evaluates, Business Details)
14. (PayPal System, Requests, Card Details)
15. (PayPal System, Evaluates, Card Details)
16. (PayPal System, Sends, Verification Email)
17. (PayPal System, Evaluates, Verification)
18. (PayPal System, Requests, Password)

Scenario 2: Country Not Accepted
1. (Personal User, Submits, Account Creation Request)
2. (Personal User, Selects, Country)
3. (PayPal System, Receives, Account Creation Request)
4. (PayPal System, Gathers, Country Information)
5. (PayPal System, Evaluates, Country)
6. (PayPal System, Generates, Error Message)

Scenario 3: Business Details Not Accepted

In [52]:
triplet_test_df

,fichier_source,texte_original,bpmn_genere,texte_reformule_llama_3_3_70b_instruct,latence_secondes_llama_3_3_70b_instruct,prompt_tokens_llama_3_3_70b_instruct,completion_tokens_llama_3_3_70b_instruct,total_tokens_llama_3_3_70b_instruct,finish_reason_llama_3_3_70b_instruct,statut_llama_3_3_70b_instruct,...,texte_reformule_llama-3.2-3b-instruct_extr_llama_3_3_70b,texte_reformule_llama-3.1-8b-instruct_extr_llama_3_3_70b,texte_reformule_mistral-small-4-119b-2603_extr_llama_3_3_70b,texte_reformule_ministral-14b-instruct-2512_extr_llama_3_3_70b,texte_reformule_mistral-nemotron_extr_llama_3_3_70b,texte_reformule_gpt-oss-20b_extr_llama_3_3_70b,texte_reformule_gpt-oss-120b_extr_llama_3_3_70b,texte_reformule_kimi-k2.6_extr_llama_3_3_70b,texte_reformule_nvidia-nemotron-nano-9b-v2_extr_llama_3_3_70b,texte_reformule_qwen3-coder-480b-a35b-instruct_extr_llama_3_3_70b
0,PAGED/1934621887.txt,"For Personal Users: To begin, send a request f...",None,The process begins when a request for account ...,14.99,507.0,491.0,998.0,stop,Succès,...,Aucun texte à analyser,Scenario 1: Successful Account Creation\n1. (P...,Erreur d'extraction : Error code: 429 - {'stat...,Scenario 1: Successful Account Creation\n1. (U...,Scenario 1: Successful Account Creation for Pe...,Scenario 1: Successful Account Creation\n1. (U...,Scenario 1: Successful Account Creation\n1. (U...,Scenario 1: Successful Account Creation\n1. (P...,Scenario 1: Personal User Account Creation \n1...,Scenario 1: Successful Account Creation\n1. (P...

In [53]:
# Exporter le DataFrame de test des triplets en fichier CSV
triplet_test_df.to_csv("triplet_test_extraction.csv", index=False, encoding="utf-8")
print("Sauvegarde effectuée dans 'triplet_test_extraction.csv'")

Sauvegarde effectuée dans 'triplet_test_extraction.csv'